"""baseline - estrutura inicial do banco

Revision ID: a258aa95113f
Revises: 
Create Date: 2026-09-11 12:10:16.586877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a258aa95113f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dh_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dh_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('snk_codemp', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('serie_nfe', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('olist_admin_email', sa.String(), nullable=True),
    sa.Column('olist_admin_senha', sa.String(), nullable=True),
    sa.Column('olist_id_fornecedor_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_id_deposito_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_dias_busca_pedidos', sa.Integer(), nullable=True),
    sa.Column('olist_situacao_busca_pedidos', sa.Integer(), nullable=True),
    sa.Column('olist_id_conta_destino', sa.Integer(), nullable=True),
    sa.Column('olist_id_categoria_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_id_categoria_despesa_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_id_categoria_taxa_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_id_categoria_frete_padrao', sa.Integer(), nullable=True),
    sa.Column('olist_id_marca_padrao', sa.Integer(), nullable=True),
    sa.Column('snk_token', sa.String(), nullable=True),
    sa.Column('snk_appkey', sa.String(), nullable=True),
    sa.Column('snk_admin_email', sa.String(), nullable=True),
    sa.Column('snk_admin_senha', sa.String(), nullable=True),
    sa.Column('snk_timeout_token_min', sa.Integer(), nullable=True),
    sa.Column('snk_top_pedido', sa.Integer(), nullable=True),
    sa.Column('snk_top_venda', sa.Integer(), nullable=True),
    sa.Column('snk_top_transferencia', sa.Integer(), nullable=True),
    sa.Column('snk_top_devolucao', sa.Integer(), nullable=True),
    sa.Column('snk_top_baixa_estoque', sa.Integer(), nullable=True),
    sa.Column('snk_codvend', sa.Integer(), nullable=True),
    sa.Column('snk_codcencus', sa.Integer(), nullable=True),
    sa.Column('snk_codnat', sa.Integer(), nullable=True),
    sa.Column('snk_codnat_transferencia', sa.Integer(), nullable=True),
    sa.Column('snk_codtipvenda', sa.Integer(), nullable=True),
    sa.Column('snk_codusu_integracao', sa.Integer(), nullable=True),
    sa.Column('snk_codtab_transf', sa.Integer(), nullable=True),
    sa.Column('snk_codlocal_estoque', sa.String(), nullable=True),
    sa.Column('snk_codlocal_venda', sa.Integer(), nullable=True),
    sa.Column('snk_codlocal_ecommerce', sa.String(), nullable=True),
    sa.Column('snk_codparc', sa.Integer(), nullable=True),
    sa.Column('snk_codemp_fornecedor', sa.Integer(), nullable=False),
    sa.Column('snk_obs_transferencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_table('sankhya',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('x_token', sa.String(), nullable=False),
    sa.Column('dh_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('dh_expiracao_token', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_sankhya_app_id'), 'sankhya', ['app_id'], unique=False)
    op.create_table('ecommerce',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_loja', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_fornecedor_olist', sa.Integer(), nullable=True),
    sa.Column('id_conta_destino', sa.Integer(), nullable=False),
    sa.Column('id_categoria_financeiro', sa.Integer(), nullable=False),
    sa.Column('id_forma_pgto_padrao', sa.Integer(), nullable=True),
    sa.Column('id_forma_rec_padrao', sa.Integer(), nullable=True),
    sa.Column('id_deposito', sa.Integer(), nullable=True),
    sa.Column('dh_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dh_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('importa_pedido_lote', sa.Boolean(), nullable=True),
    sa.Column('limite_pedido_lote', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecommerce_id'), 'ecommerce', ['id'], unique=False)
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dh_execucao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('contexto', sa.String(), nullable=False),
    sa.Column('de', sa.String(), nullable=False),
    sa.Column('para', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=False)
    op.create_table('olist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dh_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('dh_expiracao_token', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('dh_expiracao_refresh_token', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_token', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_olist_id'), 'olist', ['id'], unique=False)
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codprod', sa.Integer(), nullable=False),
    sa.Column('idprod', sa.Integer(), nullable=True),
    sa.Column('dh_criacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dh_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pendencia', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_table('log_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codprod', sa.Integer(), nullable=True),
    sa.Column('idprod', sa.Integer(), nullable=True),
    sa.Column('qtdmov', sa.Integer(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('status_lotes', sa.Boolean(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_estoque_id'), 'log_estoque', ['id'], unique=False)
    op.create_table('log_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codprod', sa.Integer(), nullable=True),
    sa.Column('idprod', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(), nullable=True),
    sa.Column('valor_old', sa.String(), nullable=True),
    sa.Column('valor_new', sa.String(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_produto_id'), 'log_produto', ['id'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('dh_pedido', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('cod_pedido', sa.String(), nullable=False),
    sa.Column('num_pedido', sa.Integer(), nullable=False),
    sa.Column('dados_pedido', sa.JSON(), nullable=True),
    sa.Column('dh_cancelamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_separacao', sa.Integer(), nullable=True),
    sa.Column('nunota', sa.Integer(), nullable=True),
    sa.Column('dh_importacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dh_confirmacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dh_faturamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erro', sa.Boolean(), nullable=True),
    sa.Column('erro_descricao', sa.String(), nullable=True),
    sa.Column('ecommerce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecommerce_id'], ['ecommerce.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.create_table('shopee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_key', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('dh_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('dh_expiracao_token', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('dh_expiracao_refresh_token', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ecommerce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecommerce_id'], ['ecommerce.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopee_id'), 'shopee', ['id'], unique=False)
    op.create_table('log_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("evento IN ('R', 'I', 'C', 'F', 'N', 'D')", name='ck_log_pedido_evento'),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_pedido_id'), 'log_pedido', ['id'], unique=False)
    op.create_table('nota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('dh_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('id_financeiro', sa.Integer(), nullable=True),
    sa.Column('id_financeiro_taxa', sa.Integer(), nullable=True),
    sa.Column('id_financeiro_frete', sa.Integer(), nullable=True),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('dh_baixa_financeiro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nunota', sa.Integer(), nullable=True),
    sa.Column('dh_confirmacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baixa_estoque_ecommerce', sa.Boolean(), nullable=True),
    sa.Column('dh_cancelamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_sankhya', sa.Boolean(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('income_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_id'), 'nota', ['id'], unique=False)
    op.create_table('devolucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('dh_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('nunota', sa.Integer(), nullable=True),
    sa.Column('dh_confirmacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dh_cancelamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devolucao_id'), 'devolucao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devolucao_id'), table_name='devolucao')
    op.drop_table('devolucao')
    op.drop_index(op.f('ix_nota_id'), table_name='nota')
    op.drop_table('nota')
    op.drop_index(op.f('ix_log_pedido_id'), table_name='log_pedido')
    op.drop_table('log_pedido')
    op.drop_index(op.f('ix_shopee_id'), table_name='shopee')
    op.drop_table('shopee')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_log_produto_id'), table_name='log_produto')
    op.drop_table('log_produto')
    op.drop_index(op.f('ix_log_estoque_id'), table_name='log_estoque')
    op.drop_table('log_estoque')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('ix_olist_id'), table_name='olist')
    op.drop_table('olist')
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_ecommerce_id'), table_name='ecommerce')
    op.drop_table('ecommerce')
    op.drop_index(op.f('ix_sankhya_app_id'), table_name='sankhya')
    op.drop_table('sankhya')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
